'use client';
import { NavigationLink as Link } from '../shared';
import Image from 'next/image';
import { useState, useEffect, useRef, type FormEvent, type ReactNode } from 'react';
import { ArrowLeft, ArrowRight, ClockCounterClockwise, GearSix, House, Plus, ShieldCheck, Stethoscope, Users } from '@phosphor-icons/react';
import type { AdminView, DirectoryUser } from '../../lib/admin';
import type { AppUser } from '../../lib/auth';
import { LogoutButton } from '../logout-button';
import s from './admin.module.css';

const navigation = [ ['Visão geral', '', House], ['Pacientes', 'pacientes', Users], ['Médicos', 'medicos', Stethoscope], ['Acessos', 'acessos', ShieldCheck], ['Histórico', 'historico', ClockCounterClockwise], ['Configurações', 'configuracoes', GearSix] ] as const;
const roleLabel = { patient: 'Paciente', professional: 'Médico', admin: 'Administrador' };
const date = (value: string) => new Intl.DateTimeFormat('pt-BR', { dateStyle: 'short', timeStyle: 'short', timeZone: 'America/Sao_Paulo' }).format(new Date(value));
const initials = (name: string) => name.split(' ').slice(0, 2).map(part => part[0]).join('');
type Run = (body: Record<string, unknown>, destination?: string) => Promise<boolean>;
export function AccountShell({ user, children }: { user: AppUser; children: ReactNode }) {
  return <div className={s.shell}><div className={s.compact}><header className={s.topbar}><Link href={user.role === 'professional' ? '/medico' : `/paciente/${user.patientId}`} className={s.link}>Instituto VIVANCE</Link><span>{user.displayName}</span><LogoutButton /></header>{children}</div></div>;
}
export default function AdminWorkspace({ initial, actor, path = [], presetDoctor = '', initialFilter = 'all' }: { initial: AdminView; actor: AppUser; path?: string[]; presetDoctor?: string; initialFilter?: string }) {
  const [data, setData] = useState(initial), [busy, setBusy] = useState(false), [notice, setNotice] = useState(''), [error, setError] = useState('');
  const [search, setSearch] = useState(''), [filter, setFilter] = useState(initialFilter);
  const alertRef = useRef<HTMLParagraphElement>(null);
  useEffect(() => { if (error) alertRef.current?.focus(); }, [error]);
  const section = path[0] ?? '', id = path[1], selected = data.users.find(user => user.id === id);
  const creating = id === 'novo';
  const title = navigation.find(item => item[1] === section)?.[0] ?? 'Administração';
  const doctors = data.users.filter(user => user.role === 'professional');
  const patients = data.users.filter(user => user.role === 'patient');
  const linkFor = (userId: string) => data.links.find(link => link.patientUserId === userId);
  const doctorName = (userId: string) => data.users.find(user => user.id === linkFor(userId)?.professionalUserId)?.displayName ?? 'Sem médico vinculado';
  const run: Run = async (body, destination) => {
    if (busy) return false;
    setBusy(true); setError(''); setNotice('');
    try {
      const response = await fetch('/api/admin', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) });
      const result = await response.json() as { id?: string; error?: string };
      if (!response.ok) throw new Error(result.error ?? 'Não foi possível salvar.');
      if (destination) { window.location.assign(destination.replace(':id', result.id ?? '')); return true; }
      const fresh = await fetch('/api/admin', { cache: 'no-store' });
      if (!fresh.ok) throw new Error('A alteração foi salva. Recarregue a página para atualizar a lista.');
      setData(await fresh.json() as AdminView); setNotice('Alteração salva.'); return true;
    } catch (cause) { setError(cause instanceof Error ? cause.message : 'Tente novamente.'); return false; }
    finally { setBusy(false); }
  };
  const recordHref = (user: DirectoryUser) => `/admin/${user.role === 'patient' ? 'pacientes' : user.role === 'professional' ? 'medicos' : 'acessos'}/${user.id}`;
  const rows = (users: DirectoryUser[]) => <div className={s.rows}>{!users.length ? <p className={s.empty}>Nenhum cadastro encontrado. Ajuste a busca ou crie um cadastro.</p> : users.map(user => <div className={s.row} key={user.id}><div className={s.person}><span className={s.avatar} aria-hidden="true">{initials(user.displayName)}</span><div><strong>{user.displayName}</strong><small>{user.role === 'patient' ? doctorName(user.id) : user.role === 'professional' ? `${data.links.filter(link => link.professionalUserId === user.id).length} pacientes vinculados` : user.username}</small></div></div><div className={s.rowEnd}><span className={`${s.badge} ${user.status === 'blocked' ? s.blocked : ''}`}>{user.status === 'active' ? 'Acesso liberado' : 'Acesso bloqueado'}</span><Link className={s.link} href={recordHref(user)} aria-label={`Abrir cadastro de ${user.displayName}`}>Abrir cadastro <ArrowRight size={16} aria-hidden="true" /></Link></div></div>)}</div>;
  return <div className={s.shell}><Link className="sr-only focus:not-sr-only" href="#main-content">Ir para o conteúdo</Link><aside className={s.sidebar}><div className={s.brand}><Image src="/brand/vivance-mark.png" width={36} height={36} alt="" /> VIVANCE</div><nav aria-label="Administração">{navigation.map(([label, href, Icon]) => <Link key={href} href={`/admin${href ? `/${href}` : ''}`} className={s.navItem} aria-current={section === href ? 'page' : undefined}><Icon size={20} aria-hidden="true" />{label}</Link>)}</nav><div className={s.sidebarBottom}><strong>Administração</strong><p>Cadastros, equipe e acessos.</p></div></aside>
    <main id="main-content" className={s.main}><header className={s.topbar}><span>{data.settings.name} · Ambiente local de demonstração</span><div className={s.actions}><span>{actor.displayName}</span><LogoutButton /></div></header>
      {id && <Link href={`/admin/${section}`} className={s.back}><ArrowLeft size={16} aria-hidden="true" />Voltar para {title.toLowerCase()}</Link>}
      <div className={s.heading}><div><h1>{creating ? `Novo ${section === 'pacientes' ? 'paciente' : section === 'medicos' ? 'médico' : 'administrador'}` : selected?.displayName ?? title}</h1><p className={s.subtle}>{selected ? `${roleLabel[selected.role]} · Usuário: ${selected.username}` : creating ? 'Prepare o cadastro e defina quando liberar o acesso.' : section === '' ? 'Organize os cadastros e mantenha cada paciente com seu responsável.' : section === 'historico' ? 'Últimas 200 ações administrativas, com autoria e motivo.' : section === 'pacientes' ? 'Cadastre pacientes e organize os vínculos com a equipe.' : section === 'medicos' ? 'Gerencie os médicos e seus pacientes.' : section === 'acessos' ? 'Controle quem pode entrar no instituto.' : 'Dados de contato do instituto.'}</p></div>{!id && ['pacientes', 'medicos', 'acessos'].includes(section) && <Link className={s.button} href={`/admin/${section}/novo`}><Plus size={18} aria-hidden="true" />{section === 'pacientes' ? 'Novo paciente' : section === 'medicos' ? 'Novo médico' : 'Novo administrador'}</Link>}</div>
      {error && <p role="alert" tabIndex={-1} ref={alertRef} className={`${s.notice} ${s.error}`}>{error}</p>}{notice && <p role="status" className={s.notice}>{notice}</p>}
      {creating ? <UserForm doctors={doctors} role={section === 'pacientes' ? 'patient' : section === 'medicos' ? 'professional' : 'admin'} presetDoctor={presetDoctor} run={run} busy={busy} /> : selected ? <>
        <div className={s.panel}><UserForm key={`${selected.id}:${selected.revision}`} user={selected} doctors={doctors} role={selected.role} run={run} busy={busy} /></div>
        {selected.role === 'patient' && <section className={s.panel}><h2>Médico responsável</h2><p className={s.subtle}>{doctorName(selected.id)}{linkFor(selected.id) ? ` · desde ${date(linkFor(selected.id)!.createdAt)}` : ''}</p><LinkForm key={`link-${selected.revision}`} users={[selected]} doctors={doctors} links={data.links} run={run} busy={busy} /></section>}
        {selected.role === 'professional' && <section className={s.panel}><div className={s.heading}><h2>Pacientes vinculados</h2><Link href={`/admin/pacientes/novo?medico=${selected.id}`} className={s.secondary}>Cadastrar paciente</Link></div>{rows(patients.filter(user => linkFor(user.id)?.professionalUserId === selected.id))}<details className={s.details}><summary>Vincular pacientes existentes</summary><LinkForm key={`doctor-links-${data.events[0]?.id}`} users={patients} doctors={doctors} fixedDoctor={selected.id} links={data.links} run={run} busy={busy} /></details></section>}
        <section className={s.panel}><h2>Acesso ao aplicativo</h2><p className={s.subtle}>{selected.status === 'active' ? 'Acesso liberado' : 'Acesso bloqueado'}</p><div className={`${s.actions} mt-4`}><button className={s.secondary} disabled={busy || selected.id === actor.id && selected.status === 'active'} onClick={() => void run({ action: 'status', id: selected.id, revision: selected.revision, status: selected.status === 'active' ? 'blocked' : 'active' })}>{selected.status === 'active' ? 'Bloquear acesso' : 'Liberar acesso'}</button><button className={s.secondary} disabled={busy} onClick={() => void run({ action: 'sessions', id: selected.id, revision: selected.revision })}>Encerrar sessões</button></div><details className={s.details}><summary>Redefinir senha</summary><form className={s.form} onSubmit={event => { event.preventDefault(); const form = event.currentTarget; const password = new FormData(form).get('password'); void run({ action: 'password', id: selected.id, revision: selected.revision, password }).then(ok => { if (ok) form.reset(); }); }}><label>Nova senha<input type="password" name="password" required minLength={10} maxLength={200} autoComplete="new-password" /></label><p className={s.subtle}>A nova senha encerra as sessões abertas. Combine a entrega com a pessoa; nenhum e-mail é enviado automaticamente.</p><button className={s.button} disabled={busy}>Salvar nova senha</button></form></details></section>
        <section className={s.panel}><h2>Histórico deste cadastro</h2><History events={data.events.filter(item => item.subjectId === selected.id)} /></section>
      </> : section === '' ? <><div className={s.metrics}><Link className={s.metric} href="/admin/pacientes"><strong>{patients.length}</strong><span>Pacientes cadastrados</span></Link><Link className={s.metric} href="/admin/medicos"><strong>{doctors.filter(user => user.status === 'active').length}</strong><span>Médicos com acesso</span></Link><Link className={s.metric} href="/admin/pacientes?filtro=sem-medico"><strong>{patients.filter(user => !linkFor(user.id)).length}</strong><span>Pacientes sem médico</span></Link></div><section className={s.panel}><div className={s.heading}><h2>Pacientes sem médico responsável</h2><Link href="/admin/pacientes/novo" className={s.button}><Plus size={18} aria-hidden="true" />Novo paciente</Link></div>{patients.some(user => !linkFor(user.id)) ? rows(patients.filter(user => !linkFor(user.id))) : <p className={s.empty}>Todos os pacientes cadastrados têm um médico vinculado.</p>}</section><section className={s.panel}><h2>Últimas alterações</h2><History events={data.events.slice(0, 5)} /></section></> : section === 'historico' ? <section className={s.panel}><History events={data.events} /></section> : section === 'configuracoes' ? <section className={s.panel}><form className={s.form} onSubmit={event => { event.preventDefault(); void run({ action: 'settings', revision: data.settings.revision, ...Object.fromEntries(new FormData(event.currentTarget)) }); }}><label>Nome do instituto<input name="name" defaultValue={data.settings.name} minLength={3} maxLength={120} required /></label><label>Canal de contato<input name="contact" defaultValue={data.settings.contact} maxLength={180} /></label><label>Horário de atendimento<input name="hours" defaultValue={data.settings.hours} maxLength={180} /></label><button className={s.button} disabled={busy}>Salvar configurações</button></form></section> : <section className={s.panel}><div className={s.toolbar}><label>Buscar por nome ou usuário<input type="search" value={search} onChange={event => setSearch(event.target.value)} placeholder="Digite para buscar" /></label><label>Filtrar<select value={filter} onChange={event => setFilter(event.target.value)}><option value="all">Todos os cadastros</option><option value="active">Acesso liberado</option><option value="blocked">Acesso bloqueado</option>{section === 'pacientes' && <><option value="unlinked">Sem médico vinculado</option>{doctors.map(doctor => <option key={doctor.id} value={`doctor:${doctor.id}`}>{doctor.displayName}</option>)}</>}</select></label></div>{rows(data.users.filter(user => section === 'pacientes' ? user.role === 'patient' : section === 'medicos' ? user.role === 'professional' : true).filter(user => `${user.displayName} ${user.username}`.toLocaleLowerCase('pt-BR').includes(search.toLocaleLowerCase('pt-BR')) && (filter === 'all' ? true : filter === 'unlinked' ? !linkFor(user.id) : filter.startsWith('doctor:') ? linkFor(user.id)?.professionalUserId === filter.slice(7) : user.status === filter)))}</section>}
    </main></div>;
}
function History({ events }: { events: AdminView['events'] }) { return <div>{events.length ? events.map(item => <article key={item.id} className={s.history}><strong>{item.action} · {item.subjectName}</strong><p>{item.detail}</p><small className={s.subtle}>{item.actorName} · {date(item.createdAt)}</small></article>) : <p className={s.empty}>Nenhuma alteração registrada.</p>}</div>; }
function UserForm({ user, role, doctors, presetDoctor = '', run, busy }: { user?: DirectoryUser; role: AppUser['role']; doctors: DirectoryUser[]; presetDoctor?: string; run: Run; busy: boolean }) {
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = Object.fromEntries(new FormData(event.currentTarget)); void run({ ...data, action: user ? 'edit' : 'create', role, id: user?.id, revision: user?.revision }, user ? undefined : `/admin/${role === 'patient' ? 'pacientes' : role === 'professional' ? 'medicos' : 'acessos'}/:id`); };
  return <form className={s.form} onSubmit={submit}><fieldset disabled={busy}><legend>Dados cadastrais</legend><div className={s.grid}><label className={s.full}>Nome completo<input name="displayName" defaultValue={user?.displayName} required minLength={3} maxLength={120} autoComplete="name" /></label><label>E-mail<input name="email" type="email" defaultValue={user?.email} maxLength={180} autoComplete="email" /></label><label>Telefone<input name="phone" type="tel" defaultValue={user?.phone} maxLength={40} autoComplete="tel" /></label>{role === 'professional' && <label className={s.full}>Registro profissional (CRM / UF)<input name="professionalRegistration" defaultValue={user?.professionalRegistration} maxLength={80} placeholder="Ex.: CRM 123456 / SP" /></label>}</div></fieldset>{!user && <fieldset disabled={busy}><legend>Acesso ao aplicativo</legend><div className={s.grid}><label>Usuário<input name="username" required minLength={3} maxLength={80} pattern="[a-zA-Z0-9._\-]+" autoComplete="off" /></label><label>Senha inicial<input name="password" type="password" required minLength={10} maxLength={200} autoComplete="new-password" /></label><label>Situação inicial<select name="status" defaultValue="blocked"><option value="blocked">Preparar cadastro · acesso bloqueado</option><option value="active">Liberar acesso agora</option></select></label>{role === 'patient' && <label>Médico responsável<select name="professionalUserId" defaultValue={presetDoctor}><option value="">Vincular depois</option>{doctors.filter(item => item.status === 'active').map(item => <option key={item.id} value={item.id}>{item.displayName}</option>)}</select></label>}</div><p className={`${s.subtle} mt-4`}>Senha de pelo menos 10 caracteres. O acesso é entregue manualmente; nenhum convite é enviado automaticamente.</p></fieldset>}<div className={s.actions}><button className={s.button} disabled={busy}>{busy ? 'Salvando…' : user ? 'Salvar cadastro' : 'Criar cadastro'}</button></div></form>;
}
function LinkForm({ users, doctors, links, fixedDoctor, run, busy }: { users: DirectoryUser[]; doctors: DirectoryUser[]; links: AdminView['links']; fixedDoctor?: string; run: Run; busy: boolean }) {
  const [chosen, setChosen] = useState<string[]>(fixedDoctor ? [] : users.map(user => user.id));
  const current = links.find(link => link.patientUserId === users[0]?.id)?.professionalUserId ?? '';
  const [doctor, setDoctor] = useState(fixedDoctor ?? current), [reason, setReason] = useState(''), [query, setQuery] = useState('');
  const eligible = users.filter(user => !fixedDoctor || !links.some(link => link.patientUserId === user.id && link.professionalUserId === fixedDoctor));
  const transfers = chosen.filter(id => links.some(link => link.patientUserId === id && link.professionalUserId !== doctor));
  return <form className={`${s.form} mt-5`} onSubmit={event => { event.preventDefault(); void run({ action: 'link', professionalUserId: doctor || null, reason, patients: users.filter(user => chosen.includes(user.id)).map(user => ({ id: user.id, revision: user.revision })) }); }}>
    {fixedDoctor ? <fieldset disabled={busy}><legend>Selecionar pacientes</legend><label>Buscar paciente<input type="search" value={query} onChange={event => setQuery(event.target.value)} /></label>{eligible.filter(user => user.displayName.toLowerCase().includes(query.toLowerCase())).map(user => { const old = links.find(link => link.patientUserId === user.id); return <label className={s.check} key={user.id}><input type="checkbox" checked={chosen.includes(user.id)} onChange={event => setChosen(value => event.target.checked ? [...value, user.id] : value.filter(id => id !== user.id))} /><span>{user.displayName}<small className={`block ${s.subtle}`}>{doctors.find(item => item.id === old?.professionalUserId)?.displayName ?? 'Sem médico vinculado'}</small></span></label>; })}{!eligible.length && <p className={s.empty}>Todos os pacientes já estão vinculados a este médico.</p>}</fieldset> : <label>Médico responsável<select value={doctor} onChange={event => setDoctor(event.target.value)}><option value="">Sem médico · encerrar vínculo</option>{doctors.filter(item => item.status === 'active').map(item => <option key={item.id} value={item.id}>{item.displayName}</option>)}</select></label>}
    {transfers.length > 0 && <p className={s.notice}>{doctor ? `${transfers.length} paciente(s) será(ão) transferido(s). O novo médico terá um acompanhamento e uma conversa vazios. Os registros anteriores permanecem preservados, sem acesso automático pelo novo vínculo.` : 'O vínculo será encerrado. Os registros anteriores permanecem preservados.'}</p>}
    <label>Motivo<input value={reason} onChange={event => setReason(event.target.value)} required minLength={3} maxLength={300} placeholder="Ex.: início do acompanhamento" /></label><button className={s.button} disabled={busy || !chosen.length || !fixedDoctor && doctor === current || Boolean(fixedDoctor && !doctors.some(item => item.id === fixedDoctor && item.status === 'active'))}>{busy ? 'Salvando…' : transfers.length ? doctor ? 'Confirmar transferência' : 'Encerrar vínculo' : `Vincular ${fixedDoctor ? `pacientes (${chosen.length})` : 'médico'}`}</button>
  </form>;
}
