-- Patient invitations and a resumable, patient-owned onboarding record.
-- Invitation secrets are generated by the Edge Function and only their
-- SHA-256 hashes are stored. Clinical content is not readable by operations.

create table public.patient_invitations (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid not null references public.tenants(id),
  display_name text not null check (char_length(btrim(display_name)) between 2 and 160),
  channel text not null check (channel in ('email', 'whatsapp')),
  recipient_email text,
  recipient_phone text,
  token_hash text unique,
  doctor_id uuid not null,
  invited_by uuid not null,
  status text not null default 'pending' check (status in ('pending', 'accepted', 'revoked')),
  delivery_status text not null default 'not_applicable'
    check (delivery_status in ('requested', 'not_applicable', 'failed')),
  expires_at timestamptz not null default (clock_timestamp() + interval '7 days'),
  claimed_at timestamptz,
  accepted_at timestamptz,
  accepted_by uuid,
  patient_id uuid,
  created_at timestamptz not null default clock_timestamp(),
  updated_at timestamptz not null default clock_timestamp(),
  version integer not null default 1 check (version > 0),
  foreign key (tenant_id, doctor_id) references public.memberships(tenant_id, user_id),
  foreign key (tenant_id, invited_by) references public.memberships(tenant_id, user_id),
  foreign key (tenant_id, patient_id) references public.patients(tenant_id, id),
  check (recipient_email is null or (char_length(recipient_email) between 3 and 254 and recipient_email = lower(btrim(recipient_email)))),
  check (recipient_phone is null or recipient_phone ~ '^\+[1-9][0-9]{7,14}$'),
  check (token_hash is null or token_hash ~ '^[0-9a-f]{64}$'),
  check ((channel = 'email' and recipient_email is not null and recipient_phone is null and token_hash is null)
      or (channel = 'whatsapp' and recipient_email is null and recipient_phone is not null and token_hash is not null)
      or (channel = 'whatsapp' and recipient_email is not null and recipient_phone is not null and token_hash is null and claimed_at is not null)
      or (channel = 'whatsapp' and status = 'revoked' and recipient_phone is not null and token_hash is null)),
  check ((status = 'accepted' and accepted_at is not null and accepted_by is not null and patient_id is not null)
      or (status <> 'accepted' and accepted_at is null and accepted_by is null and patient_id is null))
);
create index patient_invitations_actor_list
  on public.patient_invitations(tenant_id, invited_by, status, created_at desc);
create index patient_invitations_recipient
  on public.patient_invitations(lower(recipient_email), status, expires_at);
create unique index patient_invitations_one_pending_email
  on public.patient_invitations(tenant_id, lower(recipient_email))
  where status = 'pending' and recipient_email is not null;

create table public.patient_onboarding (
  tenant_id uuid not null,
  patient_id uuid not null,
  user_id uuid not null,
  status text not null default 'draft' check (status in ('draft', 'submitted')),
  current_step text not null default 'profile'
    check (current_step in ('profile', 'measurements', 'questions', 'exams', 'review')),
  skipped_steps text[] not null default '{}',
  questionnaire_version text not null default 'vivance-preconsulta-v1',
  photo_document_id uuid,
  exam_document_ids uuid[] not null default '{}',
  birth_date date check (birth_date between date '1900-01-01' and current_date),
  weight_kg numeric(6,2) check (weight_kg > 0 and weight_kg <= 500),
  height_cm numeric(5,2) check (height_cm > 0 and height_cm <= 300),
  waist_cm numeric(5,2) check (waist_cm > 0 and waist_cm <= 400),
  measured_on date check (measured_on between date '1900-01-01' and current_date),
  answer_goal text not null default '' check (char_length(answer_goal) <= 4000),
  answer_history text not null default '' check (char_length(answer_history) <= 4000),
  answer_routine text not null default '' check (char_length(answer_routine) <= 4000),
  answer_treatments text not null default '' check (char_length(answer_treatments) <= 4000),
  answer_questions text not null default '' check (char_length(answer_questions) <= 4000),
  share_consent boolean not null default false,
  version integer not null default 1 check (version > 0),
  expected_version integer,
  submitted_at timestamptz,
  created_at timestamptz not null default clock_timestamp(),
  updated_at timestamptz not null default clock_timestamp(),
  primary key (tenant_id, patient_id),
  unique (tenant_id, user_id),
  foreign key (tenant_id, patient_id) references public.patients(tenant_id, id),
  foreign key (tenant_id, user_id) references public.patient_accounts(tenant_id, user_id),
  foreign key (tenant_id, photo_document_id) references public.patient_documents(tenant_id, id),
  check (skipped_steps <@ array['profile','measurements','questions','exams','review']::text[]),
  check ((status = 'draft' and submitted_at is null) or (status = 'submitted' and submitted_at is not null and share_consent))
);

create table public.patient_onboarding_submissions (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid not null,
  patient_id uuid not null,
  user_id uuid not null,
  source_version integer not null,
  current_step text not null,
  skipped_steps text[] not null,
  questionnaire_version text not null,
  photo_document_id uuid,
  exam_document_ids uuid[] not null,
  birth_date date,
  weight_kg numeric(6,2),
  height_cm numeric(5,2),
  waist_cm numeric(5,2),
  measured_on date,
  answer_goal text not null,
  answer_history text not null,
  answer_routine text not null,
  answer_treatments text not null,
  answer_questions text not null,
  share_consent boolean not null check (share_consent),
  submitted_at timestamptz not null default clock_timestamp(),
  unique (tenant_id, patient_id),
  foreign key (tenant_id, patient_id) references public.patients(tenant_id, id),
  foreign key (tenant_id, user_id) references public.patient_accounts(tenant_id, user_id),
  foreign key (tenant_id, photo_document_id) references public.patient_documents(tenant_id, id)
);
create index patient_onboarding_submission_staff
  on public.patient_onboarding_submissions(tenant_id, patient_id, submitted_at desc);

alter table public.patient_invitations enable row level security;
alter table public.patient_onboarding enable row level security;
alter table public.patient_onboarding_submissions enable row level security;
revoke all on public.patient_invitations, public.patient_onboarding,
  public.patient_onboarding_submissions from public, anon, authenticated;
grant select, update (
  current_step, skipped_steps, photo_document_id, birth_date, weight_kg,
  exam_document_ids, height_cm, waist_cm, measured_on, answer_goal, answer_history,
  answer_routine, answer_treatments, answer_questions, share_consent,
  expected_version
) on public.patient_onboarding to authenticated;
grant select on public.patient_onboarding_submissions to authenticated;

create policy patient_onboarding_read_own on public.patient_onboarding
  for select to authenticated using (
    user_id = (select auth.uid())
    and private.has_live_session()
    and private.has_tenant_role(tenant_id, array['patient'])
    and exists (
      select 1 from public.patient_accounts account
      where account.tenant_id = patient_onboarding.tenant_id
        and account.patient_id = patient_onboarding.patient_id
        and account.user_id = (select auth.uid())
    )
  );
create policy patient_onboarding_update_own on public.patient_onboarding
  for update to authenticated
  using (user_id = (select auth.uid()) and status = 'draft'
    and private.has_tenant_role(tenant_id, array['patient']))
  with check (user_id = (select auth.uid()) and status = 'draft'
    and private.has_tenant_role(tenant_id, array['patient']));
create policy patient_onboarding_submission_read_own on public.patient_onboarding_submissions
  for select to authenticated using (
    user_id = (select auth.uid())
    and private.has_tenant_role(tenant_id, array['patient'])
  );
create policy patient_onboarding_submission_read_care on public.patient_onboarding_submissions
  for select to authenticated using (
    private.has_care_access(tenant_id, patient_id)
  );

create function private.validate_patient_onboarding() returns trigger
language plpgsql security invoker set search_path = '' as $$
begin
  if (new.tenant_id, new.patient_id, new.user_id, new.created_at)
      is distinct from
     (old.tenant_id, old.patient_id, old.user_id, old.created_at) then
    raise exception 'Immutable onboarding identity' using errcode = '42501';
  end if;
  if new.expected_version is null or new.expected_version <> old.version then
    raise exception 'Stale onboarding version' using errcode = '40001';
  end if;
  if old.status = 'submitted' or (new.status, new.submitted_at) is distinct from
      (old.status, old.submitted_at) and not (
        current_user <> 'authenticated' and old.status = 'draft'
        and new.status = 'submitted' and new.submitted_at is not null
        and new.share_consent
      ) then
    raise exception 'Immutable onboarding state' using errcode = '42501';
  end if;
  if new.photo_document_id is not null and not exists (
    select 1 from public.patient_documents document
    where document.tenant_id = new.tenant_id
      and document.patient_id = new.patient_id
      and document.id = new.photo_document_id
      and document.status = 'available'
      and document.visibility = 'internal'
      and document.uploaded_by = new.user_id
      and document.content_type in ('image/jpeg', 'image/png')
  ) then
    raise exception 'Available private patient image required' using errcode = '23514';
  end if;
  if exists (
    select 1 from unnest(new.exam_document_ids) document_id
    where not exists (
      select 1 from public.patient_documents document
      where document.tenant_id = new.tenant_id
        and document.patient_id = new.patient_id
        and document.id = document_id
        and document.status = 'available'
        and document.uploaded_by = new.user_id
    )
  ) then
    raise exception 'Available private patient exams required' using errcode = '23514';
  end if;
  new.skipped_steps := array(select distinct value from unnest(new.skipped_steps) value order by value);
  new.exam_document_ids := array(select distinct value from unnest(new.exam_document_ids) value order by value);
  new.version := old.version + 1;
  new.expected_version := null;
  new.updated_at := clock_timestamp();
  return new;
end;
$$;
revoke all on function private.validate_patient_onboarding() from public, anon, authenticated;
create trigger patient_onboarding_validate before update on public.patient_onboarding
  for each row execute function private.validate_patient_onboarding();

create function public.list_my_patient_invitations()
returns table(
  id uuid, tenant_id uuid, clinic_name text, display_name text,
  status text, expires_at timestamptz, created_at timestamptz
)
language sql stable security definer set search_path = '' as $$
  select invitation.id, invitation.tenant_id, tenant.name,
    invitation.display_name, invitation.status, invitation.expires_at,
    invitation.created_at
  from public.patient_invitations invitation
  join public.tenants tenant on tenant.id = invitation.tenant_id
  join auth.users account on account.id = auth.uid()
  where private.has_live_session()
    and account.email_confirmed_at is not null
    and lower(account.email) = lower(invitation.recipient_email)
    and invitation.status = 'pending'
    and tenant.status = 'active'
    and invitation.expires_at > clock_timestamp()
  order by invitation.created_at desc, invitation.id;
$$;
revoke all on function public.list_my_patient_invitations() from public, anon;
grant execute on function public.list_my_patient_invitations() to authenticated;

create function public.list_clinic_patient_invitations(target_tenant uuid)
returns table(
  id uuid, display_name text, channel text, status text, doctor_id uuid,
  delivery_status text, expires_at timestamptz, created_at timestamptz
)
language sql stable security definer set search_path = '' as $$
  select invitation.id, invitation.display_name, invitation.channel,
    case when invitation.status = 'pending' and invitation.expires_at <= clock_timestamp()
      then 'expired' else invitation.status end,
    invitation.doctor_id, invitation.delivery_status,
    invitation.expires_at, invitation.created_at
  from public.patient_invitations invitation
  where invitation.tenant_id = target_tenant
    and (
      private.has_tenant_role(target_tenant, array['admin'])
      or (private.has_tenant_role(target_tenant, array['doctor'])
        and invitation.invited_by = auth.uid())
    )
  order by invitation.created_at desc, invitation.id
  limit 500;
$$;
revoke all on function public.list_clinic_patient_invitations(uuid) from public, anon;
grant execute on function public.list_clinic_patient_invitations(uuid) to authenticated;

create function public.revoke_patient_invitation(target_tenant uuid, target_invitation uuid)
returns boolean
language plpgsql security definer set search_path = '' as $$
declare invitation public.patient_invitations;
begin
  select * into invitation from public.patient_invitations
    where tenant_id = target_tenant and id = target_invitation for update;
  if not found then return false; end if;
  if not (
    private.has_tenant_role(target_tenant, array['admin'])
    or (private.has_tenant_role(target_tenant, array['doctor'])
      and invitation.invited_by = auth.uid())
  ) then raise exception 'Invitation revocation denied' using errcode = '42501'; end if;
  if invitation.status <> 'pending' then
    raise exception 'Invitation cannot be revoked' using errcode = '23514';
  end if;
  update public.patient_invitations set status = 'revoked', token_hash = null,
    version = version + 1, updated_at = clock_timestamp()
    where id = invitation.id;
  return true;
end;
$$;
revoke all on function public.revoke_patient_invitation(uuid, uuid) from public, anon;
grant execute on function public.revoke_patient_invitation(uuid, uuid) to authenticated;

create function public.accept_patient_invitation(target_invitation uuid, explicit_accept boolean)
returns table(invitation_id uuid, tenant_id uuid, patient_id uuid, onboarding_version integer)
language plpgsql security definer set search_path = '' as $$
declare
  invitation public.patient_invitations;
  account auth.users;
  new_patient uuid;
  relationship_status text;
begin
  if explicit_accept is distinct from true or not private.has_live_session() then
    raise exception 'Explicit verified acceptance required' using errcode = '42501';
  end if;
  select * into account from auth.users where id = auth.uid();
  if not found or account.email_confirmed_at is null then
    raise exception 'Verified email required' using errcode = '42501';
  end if;
  select * into invitation from public.patient_invitations
    where id = target_invitation for update;
  if not found or invitation.status <> 'pending'
    or invitation.expires_at <= clock_timestamp()
    or invitation.recipient_email is null
    or lower(invitation.recipient_email) is distinct from lower(account.email)
    or not exists (
      select 1 from public.tenants tenant
      where tenant.id = invitation.tenant_id and tenant.status = 'active'
    )
    or not exists (
      select 1 from public.memberships inviter
      where inviter.tenant_id = invitation.tenant_id
        and inviter.user_id = invitation.invited_by
        and inviter.role in ('admin', 'doctor') and inviter.status = 'active'
    )
    or not exists (
      select 1 from public.memberships doctor
      where doctor.tenant_id = invitation.tenant_id
        and doctor.user_id = invitation.doctor_id
        and doctor.role = 'doctor' and doctor.status = 'active'
    ) then
    raise exception 'Invitation unavailable' using errcode = '23514';
  end if;
  if exists (select 1 from public.patient_accounts existing
    where existing.tenant_id = invitation.tenant_id
      and (existing.user_id = auth.uid()))
    or exists (select 1 from public.memberships existing
      where existing.tenant_id = invitation.tenant_id and existing.user_id = auth.uid()) then
    raise exception 'Existing clinical identity cannot be overwritten' using errcode = '23505';
  end if;

  insert into public.patients(tenant_id, display_name, created_by)
    values(invitation.tenant_id, invitation.display_name, invitation.invited_by)
    returning id into new_patient;
  insert into public.memberships(tenant_id, user_id, role, status, display_name)
    values(invitation.tenant_id, auth.uid(), 'patient', 'active', invitation.display_name);
  insert into public.patient_accounts(tenant_id, user_id, patient_id)
    values(invitation.tenant_id, auth.uid(), new_patient);

  relationship_status := case
    when invitation.invited_by = invitation.doctor_id then 'active'
    else 'assigned'
  end;
  insert into public.care_relationships(
    tenant_id, patient_id, professional_id, status, created_by
  ) values(
    invitation.tenant_id, new_patient, invitation.doctor_id,
    relationship_status, invitation.invited_by
  );
  insert into public.patient_onboarding(tenant_id, patient_id, user_id)
    values(invitation.tenant_id, new_patient, auth.uid());
  update public.patient_invitations set
    status = 'accepted', accepted_at = clock_timestamp(),
    accepted_by = auth.uid(), patient_id = new_patient,
    updated_at = clock_timestamp()
  where id = invitation.id;

  return query select invitation.id, invitation.tenant_id, new_patient, 1;
end;
$$;
revoke all on function public.accept_patient_invitation(uuid, boolean) from public, anon;
grant execute on function public.accept_patient_invitation(uuid, boolean) to authenticated;

create function public.submit_patient_onboarding(
  target_tenant uuid, read_version integer, explicit_share_consent boolean
) returns integer
language plpgsql security definer set search_path = '' as $$
declare draft public.patient_onboarding;
begin
  if explicit_share_consent is distinct from true
    or not private.has_tenant_role(target_tenant, array['patient']) then
    raise exception 'Explicit sharing consent required' using errcode = '42501';
  end if;
  select * into draft from public.patient_onboarding
    where tenant_id = target_tenant and user_id = auth.uid() for update;
  if not found then raise exception 'Onboarding unavailable' using errcode = '42501'; end if;
  if draft.status <> 'draft' then return draft.version; end if;
  if draft.version <> read_version then
    raise exception 'Stale onboarding version' using errcode = '40001';
  end if;
  insert into public.patient_onboarding_submissions(
    tenant_id, patient_id, user_id, source_version, current_step, skipped_steps,
    questionnaire_version,
    photo_document_id, birth_date, weight_kg, height_cm, waist_cm, measured_on,
    exam_document_ids,
    answer_goal, answer_history, answer_routine, answer_treatments,
    answer_questions, share_consent
  ) values (
    draft.tenant_id, draft.patient_id, draft.user_id, draft.version,
    draft.current_step, draft.skipped_steps, draft.questionnaire_version, draft.photo_document_id,
    draft.birth_date, draft.weight_kg, draft.height_cm, draft.waist_cm,
    draft.measured_on, draft.exam_document_ids, draft.answer_goal, draft.answer_history,
    draft.answer_routine, draft.answer_treatments, draft.answer_questions, true
  );
  update public.patient_onboarding set status = 'submitted', share_consent = true,
    submitted_at = clock_timestamp(), expected_version = draft.version
    where tenant_id = draft.tenant_id and patient_id = draft.patient_id;
  return draft.version + 1;
end;
$$;
revoke all on function public.submit_patient_onboarding(uuid, integer, boolean) from public, anon;
grant execute on function public.submit_patient_onboarding(uuid, integer, boolean) to authenticated;

-- Patient-created onboarding files remain private while the onboarding is a
-- draft. Active linked professionals can read them only after explicit submit.
create or replace function private.document_actor_has_access(
  target_tenant uuid, target_patient uuid, target_actor uuid, target_visibility text
) returns boolean
language sql stable security definer set search_path = '' as $$
  select target_actor is not null and exists (
    select 1 from public.memberships membership
    where membership.tenant_id = target_tenant
      and membership.user_id = target_actor
      and membership.status = 'active'
      and (
        (membership.role in ('doctor', 'nurse') and exists (
          select 1 from public.care_relationships relationship
          where relationship.tenant_id = target_tenant
            and relationship.patient_id = target_patient
            and relationship.professional_id = target_actor
            and relationship.status = 'active'
        ))
        or (membership.role = 'patient'
          and target_visibility in ('internal', 'shared')
          and exists (
            select 1 from public.patient_accounts account
            where account.tenant_id = target_tenant
              and account.patient_id = target_patient
              and account.user_id = target_actor
          ))
      )
  );
$$;
revoke all on function private.document_actor_has_access(uuid, uuid, uuid, text) from public, anon;
grant execute on function private.document_actor_has_access(uuid, uuid, uuid, text) to service_role;

create or replace function private.patient_document_uploader_has_access(
  target_tenant uuid, target_patient uuid, target_uploader uuid, target_visibility text
) returns boolean
language sql stable security definer set search_path = '' as $$
  select target_uploader = auth.uid()
    and auth.uid() is not null
    and private.has_live_session()
    and (
      private.has_care_access(target_tenant, target_patient)
      or (
        target_visibility in ('internal', 'shared')
        and private.has_tenant_role(target_tenant, array['patient'])
        and exists (
          select 1 from public.patient_accounts account
          where account.tenant_id = target_tenant
            and account.patient_id = target_patient
            and account.user_id = auth.uid()
        )
      )
    );
$$;
revoke all on function private.patient_document_uploader_has_access(uuid, uuid, uuid, text) from public, anon;
grant execute on function private.patient_document_uploader_has_access(uuid, uuid, uuid, text) to authenticated;

create function private.can_staff_read_patient_document(
  target_tenant uuid, target_patient uuid, target_document uuid,
  target_uploader uuid, target_visibility text
) returns boolean
language sql stable security definer set search_path = '' as $$
  select private.has_care_access(target_tenant, target_patient)
    and (
      target_visibility = 'shared'
      or not exists (
        select 1 from public.memberships uploader
        where uploader.tenant_id = target_tenant
          and uploader.user_id = target_uploader
          and uploader.role = 'patient'
      )
      or exists (
        select 1 from public.patient_onboarding_submissions submission
        where submission.tenant_id = target_tenant
          and submission.patient_id = target_patient
          and (submission.photo_document_id = target_document
            or target_document = any(submission.exam_document_ids))
      )
    );
$$;
revoke all on function private.can_staff_read_patient_document(uuid, uuid, uuid, uuid, text) from public, anon;
grant execute on function private.can_staff_read_patient_document(uuid, uuid, uuid, uuid, text) to authenticated;

drop policy patient_documents_staff_read on public.patient_documents;
create policy patient_documents_staff_read on public.patient_documents
  for select to authenticated using (
    status = 'available' and private.can_staff_read_patient_document(
      tenant_id, patient_id, id, uploaded_by, visibility
    )
  );
create policy patient_documents_patient_read_own_internal on public.patient_documents
  for select to authenticated using (
    status = 'available' and visibility = 'internal'
    and uploaded_by = (select auth.uid())
    and private.patient_document_uploader_has_access(
      tenant_id, patient_id, uploaded_by, visibility
    )
  );

create or replace function private.can_read_patient_document_object(object_path text) returns boolean
language sql stable security definer set search_path = '' as $$
  select auth.uid() is not null and private.has_live_session() and exists (
    select 1 from public.patient_documents document
    where document.storage_path = object_path
      and (
        (document.status = 'reserved' and private.patient_document_uploader_has_access(
          document.tenant_id, document.patient_id, document.uploaded_by, document.visibility
        ))
        or (
          document.status = 'available' and (
            private.can_staff_read_patient_document(
              document.tenant_id, document.patient_id, document.id,
              document.uploaded_by, document.visibility
            )
            or (
              document.uploaded_by = auth.uid()
              and private.patient_document_uploader_has_access(
                document.tenant_id, document.patient_id,
                document.uploaded_by, document.visibility
              )
            )
            or (
              document.visibility = 'shared'
              and private.has_tenant_role(document.tenant_id, array['patient'])
              and exists (
                select 1 from public.patient_accounts account
                where account.tenant_id = document.tenant_id
                  and account.patient_id = document.patient_id
                  and account.user_id = auth.uid()
              )
            )
          )
        )
      )
  );
$$;
revoke all on function private.can_read_patient_document_object(text) from public, anon;
grant execute on function private.can_read_patient_document_object(text) to authenticated;

create function public.get_my_patient_onboarding_context(target_tenant uuid)
returns table(clinic_name text, doctor_name text)
language sql stable security definer set search_path = '' as $$
  select tenant.name, coalesce(doctor.display_name, 'Médico da clínica')
  from public.patient_accounts account
  join public.tenants tenant on tenant.id = account.tenant_id
  join public.care_relationships relationship
    on relationship.tenant_id = account.tenant_id
    and relationship.patient_id = account.patient_id
    and relationship.status in ('assigned', 'active')
  join public.memberships doctor
    on doctor.tenant_id = relationship.tenant_id
    and doctor.user_id = relationship.professional_id
    and doctor.role = 'doctor' and doctor.status = 'active'
  where account.tenant_id = target_tenant
    and account.user_id = auth.uid()
    and private.has_tenant_role(target_tenant, array['patient'])
  order by relationship.created_at
  limit 1;
$$;
revoke all on function public.get_my_patient_onboarding_context(uuid) from public, anon;
grant execute on function public.get_my_patient_onboarding_context(uuid) to authenticated;

-- Only the database owner creates invitations through the authenticated Edge
-- Function. Browser roles never receive table privileges or token hashes.
grant select, insert, update on public.patient_invitations to service_role;

create trigger patient_invitations_audit after insert or update on public.patient_invitations
  for each row execute function private.audit_change();
